// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsxicsgmjjmqefztultu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeGljc2dtamptcWVmenR1bHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNjkyOTEsImV4cCI6MjA1MTc0NTI5MX0.8_lq2bhFt_N53ocFmXGyaym3oxx8ujVObq18jKOdqRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);